### ISSUE TITLE
Doesn't find Android extension

### ISSUE THREAD

**Issue by dalewking** [Banno/Gordon#115]
**Describe the bug**
Applying the plugin to an Android project fails with:

> Android extension not found. Make sure the Android plugin is applied

I am using AGP 7.0.3 and Gradle 7.2 and 1.8.2 of Gordon (because it is closest to those versions, but it fails for 1.8.0 and 1.8.5 as well.

**Comment by joshschriever** [comment]
The only thing I can think off hand is the order you apply plugins - make sure the Android plugin is applied _before_ the Gordon plugin in your buildscript. If that's already the case, I'm not sure what would be causing this. If you paste your whole buildscript, I might be able to help debug. You could also try running the Gordon Gradle task with `--stacktrace` to see exactly where that error is coming from.

**Comment by dalewking** [comment]
So I discovered that error message I reported is actually coming from another plugin, but due to this plugin not applying. The relevant part of the stack trace is:

```
Caused by: java.lang.IllegalStateException: Gordon plugin must be applied after applying the application, library, or dynamic-feature Android plugin
        at com.banno.gordon.GordonPlugin.apply(GordonPlugin.kt:27)
        at com.banno.gordon.GordonPlugin.apply(GordonPlugin.kt:23)
```

But my plugins block looks like this:
```
plugins {
    id("com.android.application")
    kotlin("android")
// other plugins
     id("com.banno.gordon")
}
```

**Comment by joshschriever** [comment]
That's odd. Does the same thing happen if you apply Gordon directly after the Android plugin, before the others?

**Comment by dalewking** [comment]
So I have determined that if I include gordon using `buildscript.dependencies.classpath` entry in my top level build.gradle.kts file, then it works. If I try to instead specify the version in a `pluginManagement.plugins` entry in my settings.gradle.kts file then that is when it doesn't work
